package com.cnmaps

import android.graphics.Color
import android.widget.FrameLayout
import com.amap.api.maps.AMap
import com.amap.api.maps.model.Gradient
import com.amap.api.maps.model.HeatmapTileProvider
import com.amap.api.maps.model.LatLng
import com.amap.api.maps.model.TileOverlay
import com.amap.api.maps.model.TileOverlayOptions
import com.amap.api.maps.model.WeightedLatLng
import com.facebook.react.uimanager.ThemedReactContext
import org.json.JSONArray

/**
 * `<Heatmap>` child host component; holds a [TileOverlay] generated by a
 * [HeatmapTileProvider] from a weighted point set. Any prop change rebuilds it.
 */
class HeatmapView(private val reactContext: ThemedReactContext) :
  FrameLayout(reactContext) {
  private var points: List<WeightedLatLng> = emptyList()
  private var radius: Int = 20
  private var gradient: Gradient? = null
  private var aMap: AMap? = null
  private var tileOverlay: TileOverlay? = null

  fun setPointsJson(json: String?) {
    points = parsePoints(json)
    rebuild()
  }

  fun setRadiusValue(value: Int) {
    radius = if (value > 0) value else 20
    rebuild()
  }

  fun setGradientJson(json: String?) {
    gradient = parseGradient(json)
    rebuild()
  }

  fun attachTo(map: AMap) {
    aMap = map
    rebuild()
  }

  fun detach() {
    tileOverlay?.remove()
    tileOverlay = null
    aMap = null
  }

  private fun rebuild() {
    val map = aMap ?: return
    tileOverlay?.remove()
    if (points.isEmpty()) {
      tileOverlay = null
      return
    }
    val builder = HeatmapTileProvider.Builder()
      .weightedData(points)
      .radius(radius)
    gradient?.let { builder.gradient(it) }
    tileOverlay = map.addTileOverlay(
      TileOverlayOptions().tileProvider(builder.build())
    )
  }

  private fun parsePoints(json: String?): List<WeightedLatLng> {
    if (json.isNullOrEmpty()) {
      return emptyList()
    }
    return runCatching {
      val arr = JSONArray(json)
      (0 until arr.length()).mapNotNull { i ->
        val o = arr.optJSONObject(i) ?: return@mapNotNull null
        val latLng = LatLng(o.getDouble("latitude"), o.getDouble("longitude"))
        WeightedLatLng(latLng, o.optDouble("weight", 1.0))
      }
    }.getOrDefault(emptyList())
  }

  private fun parseGradient(json: String?): Gradient? {
    if (json.isNullOrEmpty()) {
      return null
    }
    return runCatching {
      val o = org.json.JSONObject(json)
      val colorsArr = o.getJSONArray("colors")
      val startArr = o.getJSONArray("startPoints")
      val colors = IntArray(colorsArr.length()) { Color.parseColor(colorsArr.getString(it)) }
      val starts = FloatArray(startArr.length()) { startArr.getDouble(it).toFloat() }
      if (colors.isEmpty() || colors.size != starts.size) null else Gradient(colors, starts)
    }.getOrNull()
  }
}
