import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * 手写侧边栏，锁定信息架构顺序：
 * 介绍 → 快速上手 → 原生配置（分厂商）→ 专题指南 → API 参考 → FAQ。
 * 新增文档页时在此登记，避免 autogenerated 打乱阅读动线。
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: '快速上手',
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/choosing-provider',
      ],
    },
    {
      type: 'category',
      label: '原生配置',
      items: [
        'native-setup/amap',
        'native-setup/baidu',
        'native-setup/tencent',
        'native-setup/mapkit',
      ],
    },
    {
      type: 'category',
      label: '专题指南',
      items: [
        'guides/coordinate-systems',
        'guides/privacy-compliance',
        'guides/migrate-from-react-native-maps',
        'guides/provider-matrix',
      ],
    },
    {
      type: 'category',
      label: 'API 参考',
      link: { type: 'doc', id: 'api/index' },
      items: [
        'api/map-view',
        'api/marker',
        'api/callout',
        'api/callout-subview',
        'api/polyline',
        'api/polygon',
        'api/circle',
        'api/overlay',
        'api/url-tile',
        'api/wms-tile',
        'api/local-tile',
        'api/heatmap',
        'api/geojson',
      ],
    },
    'faq',
  ],
};

export default sidebars;
